// Auto-generated by scripts/bundle-site.mjs — DO NOT EDIT
// This file is regenerated on every build.

export const SITE_FILES: Record<string, string> = {
  '.gitignore': `node_modules
.vitepress/cache
.vitepress/dist
`,
  '.vitepress/config.mts': `import { defineConfig } from 'vitepress';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import tailwindcss from '@tailwindcss/vite';

const __dirname = dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  title: 'Learn Anything',
  description: 'Interactive learning knowledge map',

  srcDir: resolve(__dirname, '..', 'pages'),
  outDir: resolve(__dirname, 'dist'),
  cacheDir: resolve(__dirname, 'cache'),

  themeConfig: {
    nav: [],
    sidebar: [],
  },

  vite: {
    plugins: [tailwindcss()],
    resolve: {
      alias: {
        '@data': resolve(__dirname, '..', 'topics'),
      },
    },
  },
});
`,
  '.vitepress/theme/components/Dashboard.vue': `<script setup lang="ts">
import { computed } from 'vue';
import { useI18n } from '../composables/useI18n';
import { listAllTopics } from '../composables/useTopicData';
import TopicCard from './TopicCard.vue';

const { t } = useI18n();
const topics = computed(() => listAllTopics());
</script>

<template>
  <div class="max-w-6xl mx-auto px-4 py-8">
    <!-- Header -->
    <div class="mb-10">
      <h1 class="text-3xl font-bold text-slate-900 dark:text-white tracking-tight">
        {{ t('dashboard.title') }}
      </h1>
      <p class="mt-2 text-slate-500 dark:text-slate-400 text-sm">
        {{ topics.length }} {{ topics.length === 1 ? 'topic' : 'topics' }}
      </p>
    </div>

    <!-- Empty State -->
    <div
      v-if="topics.length === 0"
      class="flex flex-col items-center justify-center py-24 text-center"
    >
      <div class="text-6xl mb-6 opacity-80">📚</div>
      <p class="text-lg font-medium text-slate-700 dark:text-slate-200 mb-2">
        {{ t('dashboard.noTopics') }}
      </p>
      <p class="text-sm text-slate-500 dark:text-slate-400 max-w-md">
        {{ t('dashboard.startLearning') }}
      </p>
    </div>

    <!-- Card Grid -->
    <div
      v-else
      class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5"
    >
      <TopicCard
        v-for="topic in topics"
        :key="topic.slug"
        :slug="topic.slug"
        :name="topic.name"
        :domain-count="topic.domainCount"
        :total-concepts="topic.totalConcepts"
        :mastered-count="topic.masteredCount"
        :percentage="topic.percentage"
      />
    </div>
  </div>
</template>
`,
  '.vitepress/theme/components/DomainPage.vue': `<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vitepress';
import { useI18n } from '../composables/useI18n';
import SessionNotes from './SessionNotes.vue';
import ExerciseView from './ExerciseView.vue';

const props = defineProps<{ slug: string; domain: string }>();

const router = useRouter();
const { t } = useI18n();

const activeTab = ref<'notes' | 'exercises'>('notes');

function backToTopic() {
  router.go(\`/topics/\${props.slug}\`);
}
</script>

<template>
  <div class="max-w-6xl mx-auto px-4 py-8">
    <!-- Back link -->
    <a
      class="inline-flex items-center gap-1.5 text-sm text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 dark:hover:text-indigo-300 hover:underline transition-colors mb-8 cursor-pointer"
      :href="\`/topics/\${slug}\`"
      @click.prevent="backToTopic"
    >
      <span>←</span>
      {{ t('domain.backToMap') }}
    </a>

    <!-- Tabs -->
    <div class="flex gap-1 mb-8 p-1 bg-slate-100 dark:bg-slate-800 rounded-xl w-fit">
      <button
        class="px-5 py-2 text-sm font-medium rounded-lg transition-all duration-200 cursor-pointer"
        :class="activeTab === 'notes'
          ? 'bg-white dark:bg-slate-700 text-slate-900 dark:text-white shadow-sm'
          : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-300'"
        @click="activeTab = 'notes'"
      >
        📝 {{ t('domain.notes') }}
      </button>
      <button
        class="px-5 py-2 text-sm font-medium rounded-lg transition-all duration-200 cursor-pointer"
        :class="activeTab === 'exercises'
          ? 'bg-white dark:bg-slate-700 text-slate-900 dark:text-white shadow-sm'
          : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-300'"
        @click="activeTab = 'exercises'"
      >
        🏋️ {{ t('domain.exercises') }}
      </button>
    </div>

    <!-- Content -->
    <SessionNotes v-if="activeTab === 'notes'" :slug="slug" :domain="domain" />
    <ExerciseView v-else :slug="slug" :domain="domain" />
  </div>
</template>
`,
  '.vitepress/theme/components/ExerciseView.vue': `<script setup lang="ts">
import { computed, ref } from 'vue';
import { useI18n } from '../composables/useI18n';
import { scanExercises, loadExerciseContent } from '../composables/useTopicData';
import type { ExerciseGroup } from '../composables/useTopicData';

const props = defineProps<{ slug: string; domain: string }>();

const { t } = useI18n();

const allGroups = computed<ExerciseGroup[]>(() => scanExercises(props.slug));
const groups = computed(() => allGroups.value);

const expandedConcept = ref<string | null>(null);
const activeFile = ref<string | null>(null);

function toggleConcept(conceptSlug: string) {
  expandedConcept.value =
    expandedConcept.value === conceptSlug ? null : conceptSlug;
  activeFile.value = null;
}

function viewFile(path: string) {
  activeFile.value = path;
}

const fileContent = computed(() => {
  if (!activeFile.value) return '';
  return loadExerciseContent(activeFile.value) || '';
});
</script>

<template>
  <!-- Empty -->
  <div v-if="groups.length === 0" class="flex flex-col items-center justify-center py-16 text-center">
    <div class="text-4xl mb-4 opacity-70">🏋️</div>
    <p class="text-slate-500 dark:text-slate-400">{{ t('domain.noExercises') }}</p>
  </div>

  <!-- Exercise panel -->
  <div v-else class="flex gap-6 min-h-[380px]">
    <!-- Concept group list -->
    <div class="w-64 shrink-0 overflow-y-auto max-h-[60vh]">
      <div class="space-y-3">
        <div
          v-for="group in groups"
          :key="group.conceptSlug"
          class="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden transition-shadow hover:shadow-sm"
        >
          <!-- Concept header -->
          <button
            class="w-full flex items-center justify-between px-4 py-3 text-left cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors"
            @click="toggleConcept(group.conceptSlug)"
          >
            <span class="text-sm font-semibold text-slate-800 dark:text-slate-200">
              {{ group.conceptName }}
            </span>
            <span
              class="text-xs text-slate-400 transition-transform duration-200"
              :class="{ 'rotate-180': expandedConcept === group.conceptSlug }"
            >
              ▼
            </span>
          </button>

          <!-- File list (expandable) -->
          <div
            v-if="expandedConcept === group.conceptSlug"
            class="border-t border-slate-100 dark:border-slate-800 px-3 py-2 bg-slate-50/50 dark:bg-slate-800/30 space-y-1"
          >
            <button
              v-for="file in group.files"
              :key="file.path"
              class="block w-full text-left px-3 py-1.5 rounded-md text-xs font-mono transition-colors cursor-pointer"
              :class="activeFile === file.path
                ? 'bg-indigo-100 dark:bg-indigo-400/20 text-indigo-700 dark:text-indigo-300 font-medium'
                : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700/50 hover:text-slate-800 dark:hover:text-slate-200'"
              @click="viewFile(file.path)"
            >
              {{ file.name }}
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Code viewer -->
    <div class="flex-1 min-w-0">
      <div
        v-if="activeFile"
        class="rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden"
      >
        <!-- File header -->
        <div class="flex items-center gap-2 px-4 py-2.5 bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800">
          <span class="w-3 h-3 rounded-full bg-red-400" />
          <span class="w-3 h-3 rounded-full bg-amber-400" />
          <span class="w-3 h-3 rounded-full bg-emerald-400" />
          <span class="ml-2 text-xs text-slate-400 font-mono">{{ activeFile.split('/').pop() }}</span>
        </div>
        <!-- Code -->
        <pre class="overflow-auto max-h-[55vh] m-0 p-5 text-sm font-mono leading-relaxed text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 whitespace-pre-wrap break-words">{{ fileContent }}</pre>
      </div>

      <!-- No file selected -->
      <div
        v-else
        class="flex items-center justify-center h-full min-h-[200px] text-slate-400 dark:text-slate-500 text-sm"
      >
        Select a file to view its content
      </div>
    </div>
  </div>
</template>
`,
  '.vitepress/theme/components/LanguageSwitch.vue': `<script setup lang="ts">
import { useI18n } from '../composables/useI18n';

const { locale, toggleLocale, t } = useI18n();
</script>

<template>
  <button
    class="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-medium rounded-lg border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-slate-200 transition-colors cursor-pointer"
    :title="locale === 'en' ? 'Switch to 中文' : '切换到 English'"
    @click="toggleLocale"
  >
    <span class="text-sm">🌐</span>
    {{ t('lang.switch') }}
  </button>
</template>
`,
  '.vitepress/theme/components/Layout.vue': `<script setup lang="ts">
import DefaultTheme from 'vitepress/theme';
import LanguageSwitch from './LanguageSwitch.vue';

const { Layout } = DefaultTheme;
</script>

<template>
  <Layout>
    <template #nav-bar-content-after>
      <LanguageSwitch />
    </template>
  </Layout>
</template>
`,
  '.vitepress/theme/components/ProgressBar.vue': `<script setup lang="ts">
defineProps<{
  value: number;
  label?: string;
}>();
</script>

<template>
  <div
    class="w-full h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden"
    role="progressbar"
    :aria-valuenow="value"
    aria-valuemin="0"
    aria-valuemax="100"
    :aria-label="label || \`\${value}%\`"
  >
    <div
      class="h-full rounded-full transition-all duration-500 ease-out"
      :class="value === 100
        ? 'bg-gradient-to-r from-emerald-400 to-emerald-300'
        : 'bg-gradient-to-r from-indigo-400 to-indigo-300'"
      :style="{ width: \`\${value}%\` }"
    />
  </div>
</template>
`,
  '.vitepress/theme/components/SessionNotes.vue': `<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useI18n } from '../composables/useI18n';
import { scanSessions, loadMarkdown } from '../composables/useTopicData';
import type { SessionFile } from '../composables/useTopicData';

const props = defineProps<{ slug: string; domain: string }>();

const { t } = useI18n();

const files = computed<SessionFile[]>(() => scanSessions(props.slug, props.domain));
const activePath = ref<string | null>(null);

// Auto-select first file when files change
watch(
  files,
  (newFiles) => {
    if (newFiles.length > 0 && !newFiles.find((f) => f.path === activePath.value)) {
      activePath.value = newFiles[0].path;
    }
  },
  { immediate: true },
);

const selectedContent = computed(() => {
  if (!activePath.value) return '';
  return loadMarkdown(activePath.value) || '';
});
</script>

<template>
  <!-- Empty -->
  <div v-if="files.length === 0" class="flex flex-col items-center justify-center py-16 text-center">
    <div class="text-4xl mb-4 opacity-70">📝</div>
    <p class="text-slate-500 dark:text-slate-400">{{ t('domain.noNotes') }}</p>
  </div>

  <!-- Two-column layout -->
  <div v-else class="flex gap-6 min-h-[420px]">
    <!-- File list sidebar -->
    <div class="w-56 shrink-0 border-r border-slate-200 dark:border-slate-800 pr-4 overflow-y-auto max-h-[60vh]">
      <div class="text-xs font-semibold uppercase tracking-wider text-slate-400 dark:text-slate-500 mb-3 pl-2">
        Sessions
      </div>
      <nav class="space-y-0.5">
        <button
          v-for="file in files"
          :key="file.path"
          class="block w-full text-left px-3 py-2 rounded-lg text-xs transition-colors cursor-pointer"
          :class="file.path === activePath
            ? 'bg-indigo-50 dark:bg-indigo-400/10 text-indigo-600 dark:text-indigo-400 font-medium'
            : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-slate-200'"
          @click="activePath = file.path"
        >
          {{ file.filename }}
        </button>
      </nav>
    </div>

    <!-- Content -->
    <div class="flex-1 min-w-0">
      <div class="p-6 bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800">
        <pre class="whitespace-pre-wrap break-words font-sans text-sm leading-relaxed text-slate-700 dark:text-slate-300 p-0 m-0 bg-transparent">{{ selectedContent }}</pre>
      </div>
    </div>
  </div>
</template>
`,
  '.vitepress/theme/components/StatusIcon.vue': `<script setup lang="ts">
import type { ConceptStatus } from '../composables/useTopicData';

defineProps<{
  status: ConceptStatus;
}>();
</script>

<template>
  <span
    class="inline-flex items-center justify-center w-2.5 h-2.5 rounded-full shrink-0"
    :class="{
      'bg-emerald-400 ring-2 ring-emerald-400/30': status === 'mastered',
      'bg-amber-400 ring-2 ring-amber-400/30 animate-pulse': status === 'in_progress',
      'bg-orange-400 ring-2 ring-orange-400/30': status === 'needs_practice',
      'bg-transparent border-2 border-slate-300 dark:border-slate-600': status === 'unexplored',
    }"
  />
</template>
`,
  '.vitepress/theme/components/TopicCard.vue': `<script setup lang="ts">
import { computed } from 'vue';
import { useRouter } from 'vitepress';
import { useI18n } from '../composables/useI18n';
import ProgressBar from './ProgressBar.vue';

const props = defineProps<{
  slug: string;
  name: string;
  domainCount: number;
  totalConcepts: number;
  masteredCount: number;
  percentage: number;
}>();

const router = useRouter();
const { t } = useI18n();

const masteryVariant = computed(() => {
  if (props.percentage === 100) return 'mastered';
  if (props.percentage >= 50) return 'in_progress';
  if (props.percentage > 0) return 'started';
  return 'new';
});

const masteryLabel = computed(() => {
  if (props.percentage === 100) return t('status.mastered');
  if (props.percentage >= 50) return t('status.inProgress');
  return '';
});

const badgeClass = computed(() => {
  switch (masteryVariant.value) {
    case 'mastered':
      return 'bg-emerald-50 text-emerald-700 ring-emerald-600/20 dark:bg-emerald-400/10 dark:text-emerald-400';
    case 'in_progress':
      return 'bg-indigo-50 text-indigo-700 ring-indigo-600/20 dark:bg-indigo-400/10 dark:text-indigo-400';
    case 'started':
      return 'bg-amber-50 text-amber-700 ring-amber-600/20 dark:bg-amber-400/10 dark:text-amber-400';
    default:
      return 'bg-slate-50 text-slate-600 ring-slate-500/20 dark:bg-slate-400/10 dark:text-slate-400';
  }
});

function navigate() {
  router.go(\`/topics/\${props.slug}\`);
}
</script>

<template>
  <div
    class="group relative bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-6 cursor-pointer transition-all duration-200 hover:shadow-lg hover:border-indigo-200 dark:hover:border-indigo-800 hover:-translate-y-0.5"
    @click="navigate"
  >
    <!-- Top accent bar — colored based on mastery -->
    <div
      class="absolute top-0 left-6 right-6 h-0.5 rounded-b-full transition-colors duration-300"
      :class="{
        'bg-emerald-400': masteryVariant === 'mastered',
        'bg-indigo-400': masteryVariant === 'in_progress',
        'bg-amber-400': masteryVariant === 'started',
        'bg-slate-200 dark:bg-slate-700': masteryVariant === 'new',
      }"
    />

    <!-- Header -->
    <div class="flex items-start justify-between gap-3 pt-1">
      <h3 class="text-base font-semibold text-slate-900 dark:text-white leading-snug group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">
        {{ name }}
      </h3>
      <span
        v-if="masteryLabel"
        class="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ring-1 ring-inset shrink-0"
        :class="badgeClass"
      >
        {{ masteryLabel }}
      </span>
    </div>

    <!-- Stats -->
    <div class="mt-4 flex items-center gap-4 text-xs text-slate-500 dark:text-slate-400">
      <span class="inline-flex items-center gap-1">
        <span class="i-carbon-folder text-xs" />
        {{ domainCount }} {{ t('topic.domains') }}
      </span>
      <span class="inline-flex items-center gap-1">
        <span class="i-carbon-idea text-xs" />
        {{ totalConcepts }} {{ t('topic.concepts') }}
      </span>
      <span class="inline-flex items-center gap-1">
        <span class="i-carbon-checkmark text-xs" />
        {{ masteredCount }}/{{ totalConcepts }} {{ t('topic.mastered') }}
      </span>
    </div>

    <!-- Progress -->
    <div class="mt-4 flex items-center gap-3">
      <span
        class="text-2xl font-bold tabular-nums"
        :class="{
          'text-emerald-500': percentage === 100,
          'text-indigo-500': percentage >= 50 && percentage < 100,
          'text-amber-500': percentage > 0 && percentage < 50,
          'text-slate-300 dark:text-slate-600': percentage === 0,
        }"
      >
        {{ percentage }}%
      </span>
      <div class="flex-1">
        <ProgressBar :value="percentage" />
      </div>
    </div>
  </div>
</template>
`,
  '.vitepress/theme/components/TopicPage.vue': `<script setup lang="ts">
import { computed } from 'vue';
import { useRouter } from 'vitepress';
import { useI18n } from '../composables/useI18n';
import { loadTopic, loadKnowledgeMap } from '../composables/useTopicData';
import type { Domain, StateV1, ConceptStatus } from '../composables/useTopicData';
import StatusIcon from './StatusIcon.vue';

const props = defineProps<{ slug: string }>();

const router = useRouter();
const { t } = useI18n();

const state = computed<StateV1 | null>(() => loadTopic(props.slug));
const knowledgeMapRaw = computed(() => loadKnowledgeMap(props.slug));

const domainList = computed<Domain[]>(() => state.value?.domains ?? []);

const totalConcepts = computed(() =>
  domainList.value.reduce((sum, d) => sum + d.concepts.length, 0),
);

const masteredCount = computed(() =>
  domainList.value.reduce(
    (sum, d) => sum + d.concepts.filter((c) => c.status === 'mastered').length,
    0,
  ),
);

const pct = computed(() =>
  totalConcepts.value > 0
    ? Math.round((masteredCount.value / totalConcepts.value) * 100)
    : 0,
);

const progressColor = computed(() => {
  if (pct.value === 100) return 'text-emerald-600 dark:text-emerald-400';
  if (pct.value >= 50) return 'text-indigo-600 dark:text-indigo-400';
  if (pct.value > 0) return 'text-amber-600 dark:text-amber-400';
  return 'text-slate-400 dark:text-slate-500';
});

function isDomainActive(domainSlug: string): boolean {
  if (typeof window !== 'undefined') {
    return window.location.pathname.includes(\`/\${props.slug}/\${domainSlug}\`);
  }
  return false;
}

function navigateToDomain(domainSlug: string) {
  router.go(\`/topics/\${props.slug}/\${domainSlug}\`);
}

function statusLabel(status: ConceptStatus): string {
  const key = status === 'in_progress' ? 'status.inProgress' : \`status.\${status}\` as any;
  return t(key);
}

function statusBadgeClass(status: ConceptStatus): string {
  switch (status) {
    case 'mastered':
      return 'text-emerald-700 dark:text-emerald-400';
    case 'in_progress':
      return 'text-amber-700 dark:text-amber-400';
    case 'needs_practice':
      return 'text-orange-700 dark:text-orange-400';
    default:
      return 'text-slate-400 dark:text-slate-500';
  }
}
</script>

<template>
  <!-- Topic found -->
  <div v-if="state" class="flex gap-8 max-w-6xl mx-auto px-4 py-8">
    <!-- Left Sidebar -->
    <aside class="w-60 shrink-0 border-r border-slate-200 dark:border-slate-800 pr-5">
      <div class="sticky top-20">
        <div class="text-xs font-semibold uppercase tracking-wider text-slate-400 dark:text-slate-500 mb-3 pl-3">
          {{ t('topic.domains') }}
        </div>

        <nav class="space-y-0.5">
          <a
            v-for="domain in domainList"
            :key="domain.slug"
            class="block px-3 py-2 rounded-lg text-sm transition-colors cursor-pointer"
            :class="isDomainActive(domain.slug)
              ? 'bg-indigo-50 dark:bg-indigo-400/10 text-indigo-600 dark:text-indigo-400 font-medium'
              : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-slate-200'"
            :href="\`/topics/\${slug}/\${domain.slug}\`"
            @click.prevent="navigateToDomain(domain.slug)"
          >
            {{ domain.name }}
          </a>
        </nav>
      </div>
    </aside>

    <!-- Right Content -->
    <div class="flex-1 min-w-0">
      <!-- Title -->
      <h1 class="text-2xl font-bold text-slate-900 dark:text-white tracking-tight">
        {{ state.topic }}
      </h1>

      <!-- Progress Summary -->
      <div class="mt-4 inline-flex items-center gap-2 px-4 py-2 bg-slate-50 dark:bg-slate-800/50 rounded-xl text-sm">
        <span class="font-semibold tabular-nums" :class="progressColor">
          {{ masteredCount }}/{{ totalConcepts }}
        </span>
        <span class="text-slate-400">·</span>
        <span class="text-slate-500 dark:text-slate-400">{{ t('topic.mastered') }}</span>
        <span class="text-slate-400">·</span>
        <span class="font-semibold tabular-nums" :class="progressColor">{{ pct }}%</span>
        <span class="text-slate-500 dark:text-slate-400">{{ t('topic.progress') }}</span>
      </div>

      <!-- Domain Sections -->
      <div class="mt-8 space-y-8">
        <section v-for="domain in domainList" :key="domain.slug">
          <h2
            class="text-lg font-semibold text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 dark:hover:text-indigo-300 hover:underline cursor-pointer transition-colors mb-4"
            @click="navigateToDomain(domain.slug)"
          >
            {{ domain.name }}
          </h2>

          <ul class="space-y-2">
            <li
              v-for="concept in domain.concepts"
              :key="concept.slug"
              class="flex flex-wrap items-baseline gap-x-2 gap-y-1 px-3 py-2.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 hover:border-slate-200 dark:hover:border-slate-700 transition-colors"
            >
              <StatusIcon :status="concept.status" class="mt-0.5" />
              <strong class="text-sm text-slate-800 dark:text-slate-200">{{ concept.name }}</strong>
              <span class="text-xs" :class="statusBadgeClass(concept.status)">
                ({{ statusLabel(concept.status) }})
              </span>
              <ul
                v-if="concept.details.length > 0"
                class="w-full mt-1 pl-5 space-y-0.5"
              >
                <li
                  v-for="detail in concept.details"
                  :key="detail"
                  class="text-xs text-slate-500 dark:text-slate-400 list-disc"
                >
                  {{ detail }}
                </li>
              </ul>
            </li>
          </ul>
        </section>
      </div>

      <!-- Empty domains -->
      <div v-if="domainList.length === 0" class="flex flex-col items-center justify-center py-20 text-center">
        <div class="text-5xl mb-4 opacity-80">🗂️</div>
        <p class="text-slate-500 dark:text-slate-400">{{ t('dashboard.noTopics') }}</p>
      </div>
    </div>
  </div>

  <!-- Topic not found -->
  <div v-else class="flex flex-col items-center justify-center py-24 text-center max-w-6xl mx-auto px-4">
    <div class="text-5xl mb-4 opacity-80">🔍</div>
    <p class="text-lg font-medium text-slate-700 dark:text-slate-200">
      Topic not found: {{ slug }}
    </p>
  </div>
</template>
`,
  '.vitepress/theme/composables/useI18n.ts': `import { ref } from 'vue';

/* ------------------------------------------------------------------ */
/*  Types                                                             */
/* ------------------------------------------------------------------ */

export type Locale = 'en' | 'zh-CN';

export type I18nKey =
  | 'dashboard.title'
  | 'dashboard.noTopics'
  | 'dashboard.startLearning'
  | 'topic.progress'
  | 'topic.domains'
  | 'topic.concepts'
  | 'topic.mastered'
  | 'domain.notes'
  | 'domain.exercises'
  | 'domain.noNotes'
  | 'domain.noExercises'
  | 'domain.backToMap'
  | 'status.mastered'
  | 'status.inProgress'
  | 'status.needsPractice'
  | 'status.unexplored'
  | 'lang.switch';

type Messages = Record<I18nKey, string>;

/* ------------------------------------------------------------------ */
/*  Message tables                                                    */
/* ------------------------------------------------------------------ */

const messages: Record<Locale, Messages> = {
  en: {
    'dashboard.title': 'Learning Dashboard',
    'dashboard.noTopics': 'No topics yet',
    'dashboard.startLearning': 'Run \`learn-anything init\` to start your first topic',
    'topic.progress': 'Progress',
    'topic.domains': 'Domains',
    'topic.concepts': 'Concepts',
    'topic.mastered': 'Mastered',
    'domain.notes': 'Notes',
    'domain.exercises': 'Exercises',
    'domain.noNotes': 'No session notes yet',
    'domain.noExercises': 'No exercises yet',
    'domain.backToMap': '← Back to Knowledge Map',
    'status.mastered': 'Mastered',
    'status.inProgress': 'In Progress',
    'status.needsPractice': 'Needs Practice',
    'status.unexplored': 'Unexplored',
    'lang.switch': '中文',
  },
  'zh-CN': {
    'dashboard.title': '学习仪表盘',
    'dashboard.noTopics': '暂无学习主题',
    'dashboard.startLearning': '运行 \`learn-anything init\` 开始你的第一个学习主题',
    'topic.progress': '学习进度',
    'topic.domains': '知识域',
    'topic.concepts': '概念',
    'topic.mastered': '已掌握',
    'domain.notes': '笔记',
    'domain.exercises': '练习',
    'domain.noNotes': '暂无笔记',
    'domain.noExercises': '暂无练习',
    'domain.backToMap': '← 返回知识地图',
    'status.mastered': '已掌握',
    'status.inProgress': '学习中',
    'status.needsPractice': '需练习',
    'status.unexplored': '未探索',
    'lang.switch': 'English',
  },
};

/* ------------------------------------------------------------------ */
/*  Shared state (singleton across components)                        */
/* ------------------------------------------------------------------ */

const STORAGE_KEY = 'learn-anything-locale';

function detectLocale(): Locale {
  if (typeof localStorage === 'undefined') return 'en';
  const stored = localStorage.getItem(STORAGE_KEY);
  if (stored === 'zh-CN' || stored === 'en') return stored;
  return 'en';
}

const locale = ref<Locale>(detectLocale());

/* ------------------------------------------------------------------ */
/*  Composable                                                        */
/* ------------------------------------------------------------------ */

export function useI18n() {
  const t = (key: I18nKey): string => {
    return messages[locale.value][key];
  };

  const toggleLocale = (): void => {
    locale.value = locale.value === 'en' ? 'zh-CN' : 'en';
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem(STORAGE_KEY, locale.value);
    }
  };

  const setLocale = (next: Locale): void => {
    locale.value = next;
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem(STORAGE_KEY, next);
    }
  };

  return { locale, t, toggleLocale, setLocale };
}
`,
  '.vitepress/theme/composables/useTopicData.ts': `/* ================================================================== */
/*  useTopicData — Data access layer                                   */
/*                                                                     */
/*  Uses Vite's import.meta.glob to resolve files at build time.        */
/*  All patterns are static string literals (required by Vite).         */
/* ================================================================== */

/* ------------------------------------------------------------------ */
/*  Types                                                             */
/* ------------------------------------------------------------------ */

export type ConceptStatus =
  | 'mastered'
  | 'in_progress'
  | 'needs_practice'
  | 'unexplored';

export interface Concept {
  name: string;
  slug: string;
  status: ConceptStatus;
  confidence: number;
  practice_count: number;
  explain_count: number;
  last_explained: string | null;
  last_practiced: string | null;
  details: string[];
}

export interface Domain {
  name: string;
  slug: string;
  concepts: Concept[];
}

export interface StateV1 {
  version: 1;
  topic: string;
  slug: string;
  created: string;
  domains: Domain[];
}

export interface TopicSummary {
  slug: string;
  name: string;
  domainCount: number;
  totalConcepts: number;
  masteredCount: number;
  percentage: number;
}

export interface SessionFile {
  /** Display filename (e.g. "2026-06-11.md") */
  filename: string;
  /** Glob key for looking up the Vue component module */
  path: string;
  /** Raw markdown content */
  content: string;
}

export interface ExerciseFile {
  name: string;
  path: string;
}

export interface ExerciseGroup {
  conceptSlug: string;
  conceptName: string;
  files: ExerciseFile[];
}

/* ------------------------------------------------------------------ */
/*  Build-time glob imports                                            */
/* ------------------------------------------------------------------ */

// All topic state.json files (eager — loaded at import time)
// Relative paths from this file's location (.vitepress/theme/composables/)
const stateModules = import.meta.glob('../../../topics/*/state.json', {
  eager: true,
  import: 'default',
}) as Record<string, StateV1>;

// All knowledge-map.md files (raw strings for rendering)
const knowledgeMapModules = import.meta.glob('../../../topics/*/knowledge-map.md', {
  eager: true,
  query: '?raw',
  import: 'default',
}) as Record<string, string>;

// Session .md files — raw strings for listing + content
const sessionRawModules = import.meta.glob(
  '../../../topics/*/sessions/*/*.md',
  { eager: true, query: '?raw', import: 'default' },
) as Record<string, string>;

// Session .md files — Vue components for rendering (lazy)
const sessionComponentModules = import.meta.glob(
  '../../../topics/*/sessions/*/*.md',
);

// Exercise files — raw strings (README, code, practice records)
const exerciseModules = import.meta.glob(
  '../../../topics/*/exercises/**/*',
  { eager: true, query: '?raw', import: 'default' },
) as Record<string, string>;

/* ------------------------------------------------------------------ */
/*  Path helpers                                                      */
/* ------------------------------------------------------------------ */

function slugFromStatePath(path: string): string {
  // ".../topics/javascript/state.json" → "javascript"
  const match = path.match(/\\/topics\\/([^/]+)\\/state\\.json$/);
  return match?.[1] || '';
}

function filenameFromPath(path: string): string {
  const parts = path.split('/');
  return parts[parts.length - 1] || '';
}

function conceptFromExercisePath(path: string): string {
  // ".../topics/javascript/exercises/variables-data-types/README.md" → "variables-data-types"
  const match = path.match(/\\/topics\\/[^/]+\\/exercises\\/([^/]+)\\//);
  return match?.[1] || '';
}

/* ------------------------------------------------------------------ */
/*  Public API                                                        */
/* ------------------------------------------------------------------ */

/**
 * Lists all available topics with summary stats.
 * Scans all state.json files imported via glob.
 */
export function listAllTopics(): TopicSummary[] {
  return Object.entries(stateModules)
    .map(([path, state]) => {
      const slug = slugFromStatePath(path);
      if (!slug || !state?.domains) return null;

      const allConcepts = state.domains.flatMap((d) => d.concepts);
      const total = allConcepts.length;
      const mastered = allConcepts.filter((c) => c.status === 'mastered').length;

      return {
        slug,
        name: state.topic || slug,
        domainCount: state.domains.length,
        totalConcepts: total,
        masteredCount: mastered,
        percentage: total > 0 ? Math.round((mastered / total) * 100) : 0,
      } satisfies TopicSummary;
    })
    .filter((t): t is TopicSummary => t !== null)
    .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Loads the full state.json data for a single topic.
 * Finds the key by matching the slug in the glob key paths.
 */
export function loadTopic(slug: string): StateV1 | null {
  for (const [path, state] of Object.entries(stateModules)) {
    if (slugFromStatePath(path) === slug) return state;
  }
  return null;
}

/**
 * Loads the raw knowledge-map.md content for a topic.
 */
export function loadKnowledgeMap(slug: string): string | null {
  for (const [path, content] of Object.entries(knowledgeMapModules)) {
    const match = path.match(/\\/topics\\/([^/]+)\\/knowledge-map\\.md$/);
    if (match?.[1] === slug) return content;
  }
  return null;
}

/**
 * Lists session note files for a given topic and domain.
 * Returns files sorted by filename (date descending).
 */
export function scanSessions(slug: string, domain: string): SessionFile[] {
  const marker = \`/topics/\${slug}/sessions/\${domain}/\`;

  return Object.entries(sessionRawModules)
    .filter(([path]) => path.includes(marker) && path.endsWith('.md'))
    .map(([path, content]) => ({
      filename: filenameFromPath(path),
      path,
      content,
    }))
    .sort((a, b) => b.filename.localeCompare(a.filename)); // date descending
}

/**
 * Returns a lazy loader for a session markdown file's Vue component.
 * Usage: \`const comp = await loadSessionComponent(path)\`
 */
export function loadSessionComponent(
  path: string,
): (() => Promise<unknown>) | null {
  return sessionComponentModules[path] ?? null;
}

/**
 * Scans exercise files grouped by concept for a given topic.
 */
export function scanExercises(slug: string): ExerciseGroup[] {
  const marker = \`/topics/\${slug}/exercises/\`;
  const state = loadTopic(slug);

  // Build concept lookup: concept-slug → concept-name
  const conceptNames: Record<string, string> = {};
  if (state?.domains) {
    for (const domain of state.domains) {
      for (const concept of domain.concepts) {
        conceptNames[concept.slug] = concept.name;
      }
    }
  }

  // Group files by concept-slug
  const groups: Record<string, ExerciseFile[]> = {};

  for (const path of Object.keys(exerciseModules)) {
    if (!path.includes(marker)) continue;

    const conceptSlug = conceptFromExercisePath(path);
    if (!conceptSlug) continue;

    if (!groups[conceptSlug]) {
      groups[conceptSlug] = [];
    }
    groups[conceptSlug].push({
      name: filenameFromPath(path),
      path,
    });
  }

  return Object.entries(groups)
    .map(([conceptSlug, files]) => ({
      conceptSlug,
      conceptName: conceptNames[conceptSlug] || conceptSlug,
      files,
    }))
    .sort((a, b) => a.conceptName.localeCompare(b.conceptName));
}

/**
 * Loads the raw content of an exercise file.
 */
export function loadExerciseContent(path: string): string | null {
  return exerciseModules[path] ?? null;
}

/**
 * Loads the raw content of a session file.
 */
export function loadMarkdown(path: string): string | null {
  return sessionRawModules[path] ?? null;
}
`,
  '.vitepress/theme/index.ts': `import type { Theme } from 'vitepress';
import DefaultTheme from 'vitepress/theme';
import Layout from './components/Layout.vue';
import Dashboard from './components/Dashboard.vue';
import TopicCard from './components/TopicCard.vue';
import TopicPage from './components/TopicPage.vue';
import DomainPage from './components/DomainPage.vue';
import SessionNotes from './components/SessionNotes.vue';
import ExerciseView from './components/ExerciseView.vue';
import ProgressBar from './components/ProgressBar.vue';
import StatusIcon from './components/StatusIcon.vue';
import LanguageSwitch from './components/LanguageSwitch.vue';
import './styles/custom.css';

export default {
  extends: DefaultTheme,
  Layout,
  enhanceApp({ app }) {
    app.component('Dashboard', Dashboard);
    app.component('TopicCard', TopicCard);
    app.component('TopicPage', TopicPage);
    app.component('DomainPage', DomainPage);
    app.component('SessionNotes', SessionNotes);
    app.component('ExerciseView', ExerciseView);
    app.component('ProgressBar', ProgressBar);
    app.component('StatusIcon', StatusIcon);
    app.component('LanguageSwitch', LanguageSwitch);
  },
} satisfies Theme;
`,
  '.vitepress/theme/styles/custom.css': `/* ================================================================== */
/*  Learn Anything — VitePress Custom Styles                           */
/* ================================================================== */

@import "tailwindcss";

/* ------------------------------------------------------------------ */
/*  Tailwind class sources                                             */
/* ------------------------------------------------------------------ */

@source "../components/**/*.vue";
@source "../composables/**/*.ts";
`,
  'env.d.ts': `/// <reference types="vitepress/client" />

declare module '*.vue' {
  import type { DefineComponent } from 'vue';
  const component: DefineComponent<object, object, unknown>;
  export default component;
}

declare module '*.md' {
  import type { DefineComponent } from 'vue';
  const component: DefineComponent<object, object, unknown>;
  export default component;
}
`,
  'package.json': `{
  "name": "learn-anything-site",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vitepress dev",
    "build": "vitepress build",
    "preview": "vitepress preview"
  },
  "dependencies": {
    "@tailwindcss/vite": "^4.3.1",
    "tailwindcss": "^4.3.1",
    "vitepress": "^1.6.4",
    "vue": "^3.5.38"
  }
}
`,
  'pages/index.md': `---
layout: home
---

<script setup>
</script>

<Dashboard />
`,
  'pages/topics/[slug].md': `<script setup>
</script>

<TopicPage :slug="$params.slug" />
`,
  'pages/topics/[slug].paths.js': `import { readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export default {
  paths() {
    const __dirname = dirname(fileURLToPath(import.meta.url));
    const topicsDir = join(__dirname, '..', '..', 'topics');

    if (!existsSync(topicsDir)) return [];

    return readdirSync(topicsDir, { withFileTypes: true })
      .filter(
        (d) =>
          d.isDirectory() &&
          existsSync(join(topicsDir, d.name, 'state.json')),
      )
      .map((d) => ({ params: { slug: d.name } }));
  },
};
`,
  'pages/topics/[slug]/[domain].md': `<script setup>
</script>

<DomainPage :slug="$params.slug" :domain="$params.domain" />
`,
  'pages/topics/[slug]/[domain].paths.js': `import { readdirSync, readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export default {
  paths() {
    const __dirname = dirname(fileURLToPath(import.meta.url));
    const topicsDir = join(__dirname, '..', '..', '..', 'topics');

    if (!existsSync(topicsDir)) return [];

    const paths = [];

    // List all topics from topics/
    const topicDirs = readdirSync(topicsDir, { withFileTypes: true }).filter(
      (d) =>
        d.isDirectory() &&
        existsSync(join(topicsDir, d.name, 'state.json')),
    );

    for (const topicDir of topicDirs) {
      const slug = topicDir.name;
      const statePath = join(topicsDir, slug, 'state.json');

      try {
        const raw = readFileSync(statePath, 'utf-8');
        const state = JSON.parse(raw);

        if (state.domains && Array.isArray(state.domains)) {
          for (const domain of state.domains) {
            if (domain.slug) {
              paths.push({ params: { slug, domain: domain.slug } });
            }
          }
        }
      } catch {
        // Skip malformed state.json
      }
    }

    return paths;
  },
};
`,
  'tsconfig.json': `{
  "extends": "../../../tsconfig.base.json",
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "preserve",
    "rootDir": ".",
    "outDir": "./.vitepress/dist",
    "types": ["vitepress/client"],
    "paths": {
      "@data/*": ["./topics/*"]
    },
    "allowImportingTsExtensions": true,
    "noEmit": true
  },
  "include": [
    "env.d.ts",
    ".vitepress/**/*.ts",
    ".vitepress/**/*.mts",
    ".vitepress/**/*.vue",
    "pages/**/*.md",
    "pages/**/*.js"
  ],
  "exclude": [
    "node_modules",
    ".vitepress/dist",
    ".vitepress/cache"
  ]
}
`,
};
